// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Messenger.SignUp.Models;

public partial class SignUpContext : DbContext
{
    public SignUpContext(DbContextOptions<SignUpContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UserAccount> UserAccounts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserAccount>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserAcco__3214EC279DA63E33");

            entity.ToTable("UserAccount");

            entity.HasIndex(e => e.Email, "email").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DateCreate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Date_Create");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(30)
                .IsFixedLength();
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(60)
                .IsFixedLength();
            entity.Property(e => e.StatusAccount).HasDefaultValue(1);
            entity.Property(e => e.Username).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}