// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Messenger.SignUp.Models;

public partial class UserAccount
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? StatusAccount { get; set; }

    public DateTime DateCreate { get; set; }

    public string Username { get; set; }

    public int AccountActive { get; set; }
}