// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Messenger.UserRol.UserRoleDb;

public partial class UserRole
{
    public Guid Id { get; set; }

    public string Roles { get; set; }

    public Guid GroupId { get; set; }

    public Guid UserId { get; set; }
}