// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Messenger.SignUp.Models.Friends;

public partial class Friend
{
    public int Id { get; set; }

    public Guid UserId { get; set; }

    public Guid FriendId { get; set; }

    public int FriendStatus { get; set; }
}