    // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Messenger.SignUp.Models.Friend;

public partial class IsHaveFriendContext : DbContext
{
    public IsHaveFriendContext(DbContextOptions<IsHaveFriendContext> options)
        : base(options)
    {
    }

    public virtual DbSet<IsHaveFriendCheck> IsHaveFriends { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IsHaveFriendCheck>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__IsHaveFr__3214EC075FD77688");

            entity.ToTable("IsHaveFriend");

            entity.Property(e => e.IsHaveFriend).HasColumnName("IsHaveFriend");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}