// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Messenger.SignUp.Models.Friend;

public partial class IsHaveFriendCheck
{
    public int Id { get; set; }

    public Guid UserId { get; set; }

    public int IsHaveFriend { get; set; }
}