// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SecretMessageApi.Models;

public partial class UserInfo
{
    public int Id { get; set; }

    public Guid IdAccount { get; set; }

    public string Name { get; set; }

    public DateTime Age { get; set; }

    public string Description { get; set; }

    public string AvartarPath { get; set; }
}